### ISSUE TITLE
数据库使用注意的问题

### ISSUE THREAD

**Issue by real-lhj** [ouc-softwareclass/OUC-Market#12]
1.将用户登录名、密码，店铺名、店铺介绍、店铺头像，商品建立数据库，建几个库？
2.彼此之间需要关联，第十周计划完成数据库部分，小组之间加强沟通

**Comment by real-lhj** [comment]
感觉还是应该使用MySQL

**Comment by JuliBoy** [comment]
应该一个建一个库，多个表就可以。不同的就可以存不同的信息。
